version: '3.8'

services:
  project-1:
    build:
      context: ./rockwell
    container_name: project-1
    ports:
      - "9459:9459"
    environment:
      - PROJECT_NAME=Project 1
    restart: unless-stopped

  project-2:
    build:
      context: ./rockwelll
    container_name: project-2
    ports:
      - "9459:9459"
    environment:
      - PROJECT_NAME=Project 2
    restart: unless-stopped
